version: "3.8"

services:
  web:
    container_name: web
    image: gksrywls97/bulletbox:web
    ports:
      - 8080:8080
    depends_on:
      - redis
    networks:
      - web-net

  redis:
    image: gksrywls97/bulletbox:redis
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    container_name: redis
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always
    networks:
      - web-net

  networks:
    web-net:
      driver: bridge