version: "3.8"

services:
  web:
    container_name: web
    image: gksrywls97/bulletbox:web
    ports:
      - 8080:8080
    depends_on:
      - redis
    networks:
      - default

  redis:
    image: gksrywls97/bulletbox:redis
    command: redis-server
    container_name: redis
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always
    networks:
      - default